# Build stage
FROM node:lts-alpine as build
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend .
RUN npm run build

# Production stage
FROM node:lts-alpine
ENV NODE_ENV=production
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist
EXPOSE 2800
USER node
CMD ["serve", "-s", "dist", "-l", "2800"]
